### PR TITLE
Added lib-monitor, had to bootstrap

### PR DESCRIPTION
**Pull request by jonasfj**
Does this look sane to you...

### CODE REVIEW

**Comment by jonasfj** [comment]
note, we should let @djmitche merge this as he is reviewing the PR I'm merging into... So let him finish that review first... when he is back from PTO.

**Comment by jonasfj** [comment]
okay, we should pass monitor into api... and more?

**Comment by imbstack** [comment]
## r+

This looks good to me. I'm excited to get this into auth.

**Comment by djmitche** [comment]
Not sure what "had to bootstrap" means, but this looks good to me

**Comment by jonasfj** [comment]
Had to bootstrap monitor... as auth provides credentials for tc-lib-monitor... Maybe it should have been more descriptive..

**Pull request merged**
