### PR TITLE
Try with 1500

### PR DESCRIPTION
**Pull request by jonasfj**
Let's see if this works on travis... (honestly I care little for travis it's so unreliable already).

5s is a bit much... it'll sleep for this time before npm test terminates... so... kind of want to be small...

### CODE REVIEW

**Comment by petemoore** [comment]
Why not, let's give it a shot.

**Comment by jonasfj** [comment]
lol, we didn't need to merge to test it :)

**Comment by petemoore** [comment]
I thought you wanted to merge your pull request into mine!

**Comment by jonasfj** [comment]
ah,

**Comment by jonasfj** [comment]
I didn't see that...

**Pull request merged**
