### PR TITLE
[WIP] Bug 1242753 solution v.0.1

### PR DESCRIPTION
**Pull request by owlishDeveloper**
@imbstack @djmitche feedback will be greatly appreciated!

### CODE REVIEW

**Comment by imbstack** [comment]
When I run the tests locally, I get the following error: 

```
  1) "before all" hook

  0 passing (517ms)
  1 failing

  1)  "before all" hook:

      AssertionError: context key 'resolver' was not declared in Entity.configure
      + expected - actual

      -false
      +true
      
      at node_modules/azure-entities/lib/entity.js:633:5
      at node_modules/lodash/index.js:3073:15
      at Function.forIn (node_modules/lodash/index.js:3362:16)
      at Function.Entity.setup (node_modules/azure-entities/lib/entity.js:632:5)
      at setup (lib/main.js:138:26)
      at node_modules/taskcluster-lib-loader/lib/loader.js:324:28
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
      at node_modules/promise/lib/core.js:123:15
      at flush (node_modules/promise/node_modules/asap/raw.js:50:29)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickDomainCallback (internal/process/next_tick.js:122:9)



npm ERR! Test failed.  See above for more details.

```

Is that happening for you as well or have I cloned it incorrectly?

**Comment by owlishDeveloper** [comment]
I'm not able to test it. `npm test` wants `user-config.yml`, and as far as I understand, to fill in the `user-config.yml` I needed to run `npm run checkStagingSetup` (it says to copy-paste the results of the command into the `user-config.yml` in README) or to just get the info from you, for example.

Thanks for the error, I'll try to look and see what happens there!

**Comment by owlishDeveloper** [comment]
I deleted my previous comment because I just tried to run the test with empty user-config.yml, and it worked :) I got the same output as you.

So, I made some changes and tried to test i again. Got this error:
```

1) "before all" hook

  0 passing (2s)
  1 failing

  1)  "before all" hook:
     AuthenticationFailedError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:6821e318-0002-007c-424b-2a623f000000
Time:2016-10-19T20:56:50.0575936Z
      at node_modules/fast-azure-storage/lib/table.js:482:27
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
      at node_modules/promise/lib/core.js:123:15
      at flush (node_modules/promise/node_modules/asap/raw.js:50:29)
```
Is it because of my changes, or is it because of the empty configuration file, can you tell? I tried looking at `node_modules/fast-azure-storage/lib/table.js` - there's an error constructor there, doesn't make sense to me.

**Comment by imbstack** [comment]
I suspect that's because of the empty `user-config.yml`. Probably the easiest thing to do here will be to give you permissions to push a branch to this repo so that the tests can run in travis. Give me a sec to set that up!

**Comment by owlishDeveloper** [comment]
I'm closing thisone and creating new, from my branch

**Pull request closed without merging**
