### PR TITLE
fix spelling errors

### PR DESCRIPTION
**Pull request by djmitche**
As found in taskcluster/taskcluster-cli#100

### CODE REVIEW

**Comment by djmitche** [comment]
I'll keep pushing to my own repo as a reminder that we should be writing test automation so that it's usable by non-employees :)

**Comment by jonasfj** [comment]
Fair point :)

Den 14. feb. 2017 10.26 AM skrev "Dustin J. Mitchell" <
notifications@github.com>:

**Comment by petemoore** [comment]
@djmitche @jonasfj bizarrely, this change seems [not to have propagated](http://schemas.taskcluster.net/auth/v1/create-client-response.json).

What is even stranger, is it looks like it did propagate at some point, but then regressed, since [this commit](https://github.com/taskcluster/taskcluster-client-go/commit/09445791ef444a8cfba552c325cd8ee88f328386#diff-a2caf70f51a48b706e720c623acfe14bR211) shows that at some point the json schema must have been successfully published. Notice how the diff is the wrong way around, it shows the schema change being reverted, rather than applied.

Is there any automation that could be publishing stale schemas?

**Comment by djmitche** [comment]
Staging was set to publish.. oops!

I fixed that, and I also deployed this change to prod.

**Pull request merged**
