### PR TITLE
Bug 1434369 - don't try to create tables / containers every time

### PR DESCRIPTION
**Pull request by djmitche**
This isn't the most sophisticated way to do this, but I think it should be adequate..

### CODE REVIEW

**Comment by djmitche** [comment]
@jonasfj when you do review this, please deploy it too.  It should cut down on the error rate in auth..

**Comment by jonasfj** [comment]
A neat class with a method to wrap a function could also be nice...
```js
const createTableCache = new Cache();

...
  await createTableCache(key, async () => {
     azure.createTable(key);
  });
```

Ideally we could then create `const createTableCache = new Cache();` on the `context` object in `main.js`...
But this is also fine, if tests pass I doubt there are any bad side-effects...

**Comment by djmitche** [comment]
I like that better, and it's a bit more testable.

**Comment by djmitche** [comment]
Honestly, that kind of turns this into a big deal -- suddenly main.js has to create two objects whose only purpose is to create Azure tables, etc.  I'll land this as-is.

**Comment by jonasfj** [comment]
Fair point... We can always make this nicer later...

Note. I'm mostly concerned for side effects when testing.. but clearly tests pass here..

**Pull request merged**
